### ISSUE TITLE
It's showing an issue like, Failed to load response from ChatGPT:

### ISSUE THREAD

**Issue by nithinreddyy** [hunkimForks/chatgpt-arxiv-extension#12]
I've installed the chrome extensions and done some changes in the brave browser and the chrome too. I'm able to use that extension to get the normal outputs, but i don't know why it's showing the error on the arxiv.

![image](https://user-images.githubusercontent.com/56256685/218550377-d30d9939-b5da-4889-b0ec-dedeb0688a8a.png)

And below, you can see, the extension is not working for arxiv, instead it is working normally

![image](https://user-images.githubusercontent.com/56256685/218550518-692a9e06-f54a-4876-8a89-ab86354b8c6d.png)

Can you please let me know how to fix this?

**Comment by hunkim** [comment]
> done some changes in the brave browser and the chrome too.

What did you change?

Can you use the current version? If you see this, you are using the current version. 

<img width="829" alt="image" src="https://user-images.githubusercontent.com/901975/218593777-fd18ada2-4614-4d3c-b29a-1f01d640b20b.png">

**Comment by nithinreddyy** [comment]
> > done some changes in the brave browser and the chrome too.
> 
> What did you change?
> 
> Can you use the current version? If you see this, you are using the current version. 
> 
> <img width="829" alt="image" src="https://user-images.githubusercontent.com/901975/218593777-fd18ada2-4614-4d3c-b29a-1f01d640b20b.png">
> 

Ok. So, have you updated the version of the ArxivGPT and want to me to try that?

**Comment by nithinreddyy** [comment]
> > done some changes in the brave browser and the chrome too.
> 
> What did you change?
> 
> Can you use the current version? If you see this, you are using the current version.
> 
> <img alt="image" width="829" src="https://user-images.githubusercontent.com/901975/218593777-fd18ada2-4614-4d3c-b29a-1f01d640b20b.png">

It is working right now. But I do have one doubt. Please check the below image

![nnn](https://user-images.githubusercontent.com/56256685/218658602-d186d388-e554-4215-acca-75b6968fd176.png)

And I do have one doubt. Will it open the pdf file of the research paper, read it, and return the output, or will it return the output based solely on the homepage's content?

**Comment by nithinreddyy** [comment]
And for some of the papers, it is not returning the complete output. For example, you can see the below image

![image](https://user-images.githubusercontent.com/56256685/218661745-d75ec7b3-e940-4c24-9870-8fc9a9c8b9f6.png)

As I am a frequent user of ChatGPT, I used to take the last input sentence i.e. from the above image I'll take and ask question to ChatGPT that

Can you please continue the above from Yang, Z., Hu, B., Salakhutdinov, R., & Cohen, W. W. (2016). Multi-modal joint learning with application to image and video annotation. In Proceedings?

And it'll continue from the above. Can you update the code in the same way?

**Comment by hunkim** [comment]
I added input box. You may ask continue.

**Comment by nithinreddyy** [comment]
> I added input box. You may ask continue.

I have uninstalled and installed the new version. But i'm unable to see any input box where i can ask. Below is the image for reference

![image](https://user-images.githubusercontent.com/56256685/218747673-f3de9df0-eed1-4382-8260-434530a1fa59.png)

**Comment by hunkim** [comment]
It seems all is OK. Otherwise, please reopen this.

**Comment by nithinreddyy** [comment]
Yes, you have added an input box to it. But the input of the user and the output which ChatGPT gave are correct (but incomplete) and the continue box which you have added is not connected to previous output which ChatGPT gave. So, if i ask any question in the continue box it's like asking a new question to ChatGPT. I'll attach an image for you reference

![image](https://user-images.githubusercontent.com/56256685/219961573-7fa9d9b8-4c5c-4151-b685-63a7b82e5e4e.png)

Can you please look into this as this is one of the key issues?
