### ISSUE TITLE
The creator of this extension is still sleeping. Don't disturb him anymore. 

### ISSUE THREAD

**Issue by AranyaiitrGit** [hunkimForks/chatgpt-arxiv-extension#25]
Those who wants to use chatGPT for ieee xplore or other sites, use this extension:
https://chrome.google.com/webstore/detail/readergpt-chatgpt-based-w/ohgodjgnfedgikkgcjdkomkadbfedcjd/related

**Comment by hunkim** [comment]
@AranyaiitrGit Please check #24
