### ISSUE TITLE
[Bug] with chatgpt PRO

### ISSUE THREAD

**Issue by hunkim** [hunkimForks/chatgpt-arxiv-extension#3]
<img width="507" alt="image" src="https://user-images.githubusercontent.com/901975/218238344-55e96249-4223-48b6-a073-43ab69788bb9.png">

Perhaps current gpt api call does not work with chatgpt pro.

**Comment by sazzy4o** [comment]
Looks like this has been fixed upstream:
https://github.com/wong2/chatgpt-google-extension/issues/243#issuecomment-1426678080

Probably just need to merge upstream changes (and resolve conflicts)

**Comment by hunkim** [comment]
Thanks! 

https://github.com/hunkimForks/chatgpt-arxiv-extension/commit/a051cac8a050c994a9c30d5ca1f377a3be5a1a90

Done!
