### ISSUE TITLE
Plugin not working on Chrome: refused to connect

### ISSUE THREAD

**Issue by alissanguyen** [hunkimForks/chatgpt-arxiv-extension#37]
**Describe the bug**
Plugin not working on Chrome browser. Error: Chat.open.ai refused to connect. AI provider i'm using: ChatGPT Webapp.

**Desktop (please complete the following information):**
 - OS: Mac Sonoma 14.4.1 
 - Browser - Chromer Version 123.0.6312.106

![Screenshot 2024-04-26 at 1 31 35 PM](https://github.com/hunkimForks/chatgpt-arxiv-extension/assets/69443738/214dd7db-a377-48fc-8d02-0b8893b60382)

**Comment by legendof-selda** [comment]
same but in edge

**Comment by hunkim** [comment]
I will fix this in a few days!

**Comment by hunkim** [comment]
Now, you can use solar API key. please try!
